name: Gitlab Status
description: Reports the build status back to gitlab
author: https://github.com/buildkite-plugins
requirements:
  - curl
configuration:
  properties:
    check-name:
      type: string
    gitlab-url:
      type: string
    token-var-name:
      type: string
  required: []
  additionalProperties: false