steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.3.0:
        files:
          - hooks/**
          - lib/**

  - label: ":sparkles:"
    plugins:
      plugin-linter#v3.1.0:
        id: gitlab-status

  - label: "🔨 Tests"
    plugins:
      - plugin-tester#v1.0.0: ~


