steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.3.0:
        files: hooks/**

  - label: ":sparkles:"
    plugins:
      plugin-linter#v3.1.0:
        id: gitlab-status

  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v4.11.0:
        run: tests
