#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "$DIR/../lib/plugin.bash"


if [ "${BUILDKITE_PROJECT_PROVIDER}" != 'gitlab' ]; then
  echo '+++ Provider is not gitlab, can not do anything'
  exit 1
fi

GITLAB_TOKEN_ENV_VAR=$(plugin_read_config TOKEN_VAR_NAME "GITLAB_ACCESS_TOKEN")
if [ -n ${!GITLAB_TOKEN_ENV_VAR} ]; then
  echo '+++ ERROR: gitlab access token not configured'
  exit 1
fi

STATUS_NAME=$(plugin_read_config CHECK_NAME "${BUILDKITE_STEP_KEY}")
GITLAB_URI=$(plugin_read_config GITLAB_URL "gitlab.com")

TOKEN="${!GITLAB_TOKEN_ENV_VAR}"

CURL_CMD=(
  curl --request POST
  # TODO: move this to be last value added before executing so it is never printed out
  --header "PRIVATE-TOKEN: ${TOKEN}"
)

VARS=(
  "target_url=${BUILDKITE_BUILD_URL}"
  "name=${STATUS_NAME}"
)

ARGUMENTS=$(IFS='&'; echo "${VARS[@]}")

CURL_CMD+=("\"https://${GITLAB_URI}/api/v4/projects/17/statuses/${BUILDKITE_COMMIT}?state=success&${ARGUMENTS}\"")

"${CURL_CMD[@]}"