#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"

# BUILDKITE_COMMAND_EXIT_STATUS is not set in cases when the environment hook terminates with an error
# Defaulting it to empty makes the comparison fail and the build gets marked correctly as failure
if [ "${BUILDKITE_COMMAND_EXIT_STATUS:-}" -eq 0 ]; then
  status="success"
else
  status="failed"
fi

set_status "${status}"