#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "$DIR/../lib/plugin.bash"
# shellcheck source=lib/urls.bash
. "$DIR/../lib/urls.bash"


if [ "${BUILDKITE_PROJECT_PROVIDER}" != 'gitlab' ]; then
  echo '+++ Provider is not gitlab, can not do anything'
  exit 1
fi

GITLAB_TOKEN_ENV_VAR=$(plugin_read_config TOKEN_VAR_NAME "GITLAB_ACCESS_TOKEN")
if [ -z "${!GITLAB_TOKEN_ENV_VAR:-}" ]; then
  echo "+++ ERROR: gitlab access token not configured in variable ${GITLAB_TOKEN_ENV_VAR}"
  exit 1
fi

GITLAB_URI=$(plugin_read_config GITLAB_URL "gitlab.com")
PROJECT_SLUG=$(urlencode "$(echo "${BUILDKITE_REPO##*"${GITLAB_URI}"}" | cut -c 2- )")

STATUS_NAME=$(plugin_read_config CHECK_NAME "${BUILDKITE_STEP_KEY}")

TOKEN="${!GITLAB_TOKEN_ENV_VAR}"

CURL_CMD=(
  curl --request POST
  # TODO: move this to be last value added before executing so it is never printed out
  --header "PRIVATE-TOKEN: ${TOKEN}"
)

VARS=(
  "target_url=${BUILDKITE_BUILD_URL}"
  "name=${STATUS_NAME}"
)

ARGUMENTS=$(IFS='&'; echo "${VARS[*]}")

CURL_CMD+=("https://${GITLAB_URI}/api/v4/projects/${PROJECT_SLUG}/statuses/${BUILDKITE_COMMIT}?state=success&${ARGUMENTS}")

"${CURL_CMD[@]}"